trigger:
- master

# TODO Parameterize templates?: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
# TODO Determine if a plan file should be used: https://www.terraform.io/docs/commands/plan.html#security-warning
# TODO Look into automatically downloaded artifacts: https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-artifacts.md#automated-download-behavior---job-vs-deployment
# https://github.com/microsoft/azure-pipelines-yaml/issues/215

variables:
  # This is required so we can pass our json variables files between stages until this is resovled:
  # https://github.com/microsoft/azure-pipelines-tasks/issues/4743
  INFRASTRUCTURE_VARIABLES: 'infrastructure-variables'
  #TODO Pass this in
  ENVIRONMENT: 'dev'

stages:
 - template: templates/infrastructure-stage.yml
 - template: templates/dotnet-build-stage.yml 
 - template: templates/dotnet-deploy-stage.yml