#!/bin/bash

if [[ $# -lt 2 || "$1" == "" ]]; then
   echo "The .tfvars.json path and the terraform managed state conatiner parameters are required:"
   echo "init_terraform {relative_path:string} {managed_state:bool}"
   exit 1
else
    # TODO Make own Dockerfile to handle this
    # Check if jq is installed, if not install it for parsing JSON
    echo "Installing dependencies ......"
    dpkg -l | grep -qw jq || apt-get update > /dev/null && apt-get install -y jq > /dev/null
    
    ACCOUNTS=$(az account list --refresh --query '[].id' | jq '.[]') 
    if [ -z "$ACCOUNTS" ]
    then
        az login
    fi

    if [[ "$2" == true ]]; then
        cd ./mutable 
        ../init_terraform $1 $2
    else
        cd ./immutable 
        ../init_terraform $1 $2
    fi
fi
