#!/bin/bash
if [[ $# -lt 1 || "$1" == "" ]]; then
   echo "The .tfvars.json path parameter is required:"
   echo "init_terraform {relative_path:string}"
   exit 1
else
    #Path to terraform configs
    export TERRAFORM_ENV_VARIABLES=$1
    export TERRAFORM_VARIABLES=global.tfvars.json #TODO Pass this in?

    # Load variables from the terraform config, using 'jq' to parse the variables
    export APP_NAME=$(cat $TERRAFORM_VARIABLES | jq -r .name)
    export ENVIRONMENT=$(cat $TERRAFORM_ENV_VARIABLES | jq -r .environment)
    export LOCATION=$(cat $TERRAFORM_VARIABLES | jq -r .location)
    export PLAN_TIER=$(cat $TERRAFORM_ENV_VARIABLES | jq -r .plan_tier)
    export REPLICATION_TYPE=$(cat $TERRAFORM_ENV_VARIABLES | jq -r .storage_replication)
    export TERRAFORM_BACKEND_STATE_CONTAINER_NAME=$(cat $TERRAFORM_VARIABLES | jq -r .terraform_backend_state_container_name)
    export TERRAFORM_STATE_FILENAME=$ENVIRONMENT.terraform.tfstate

    # Setup azure parameters
    export RESOURCE_GROUP_NAME=infrastructure-$APP_NAME-$ENVIRONMENT-rg
    export STORAGE_ACCOUNT_NAME=infra${ENVIRONMENT}
    export STORAGE_ACCOUNT_SKU=${PLAN_TIER}_${REPLICATION_TYPE}
    export STORAGE_CONTAINER_URL=https://$STORAGE_ACCOUNT_NAME.blob.core.windows.net/$TERRAFORM_BACKEND_STATE_CONTAINER_NAME
fi