#!/bin/bash

# Initialize terraform to use our storage account for remote storage
terraform init \
    -backend-config="resource_group_name=$RESOURCE_GROUP_NAME" -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" -backend-config="container_name=$TERRAFORM_BACKEND_STATE_CONTAINER_NAME" -backend-config="key=$TERRAFORM_STATE_FILENAME"